config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers =>  { registrations: 'registrations' }
  resources :my_tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "my_tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_tweet.rb
class MyTweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :my_tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_tweets_controller.rb
class MyTweetsController < ApplicationController
  before_action :set_my_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /my_tweets
  # GET /my_tweets.json
  def index
    @my_tweets = MyTweet.all.order('created_at DESC')
    @my_tweet = MyTweet.new
  end

  # GET /my_tweets/1
  # GET /my_tweets/1.json
  def show
  end

  # GET /my_tweets/new
  def new
    @my_tweet = current_user.my_tweet.build
  end

  # GET /my_tweets/1/edit
  def edit
  end

  # POST /my_tweets
  # POST /my_tweets.json
  def create
    @my_tweet = current_user.my_tweet.build(my_tweet_params)

    respond_to do |format|
      if @my_tweet.save
        format.html { redirect_to root_path, notice: 'My tweet was successfully created.' }
        format.json { render :show, status: :created, location: @my_tweet }
      else
        format.html { render :new }
        format.json { render json: @my_tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_tweets/1
  # PATCH/PUT /my_tweets/1.json
  def update
    respond_to do |format|
      if @my_tweet.update(my_tweet_params)
        format.html { redirect_to @my_tweet, notice: 'My tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_tweet }
      else
        format.html { render :edit }
        format.json { render json: @my_tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_tweets/1
  # DELETE /my_tweets/1.json
  def destroy
    @my_tweet.destroy
    respond_to do |format|
      format.html { redirect_to my_tweets_url, notice: 'My tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_tweet
      @my_tweet = MyTweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def my_tweet_params
      params.require(:my_tweet).permit(:mytweet)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_tweets_helper.rb
module MyTweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class='notification is-primary global-notification'>
        <p class='notice'><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class='notification is-danger global-notification'>
        <p class='alert'><%= alert %></p>
      </div>
    <% end %>
    <nav class='navbar is-info'>
      <div class='navbar-brand'>
        <%= link_to root_path, class: 'navbar-item' do %>
          <h1 class='title is-5'>My Twitter</h1>
        <% end %>
        <div class='navbar-burger burger' data-target='navbarExample'>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id='navbarExample' class='navbar-menu'>
        <div class='navbar-end'>
          <div class="navbar-item navbar-end">
            <div class='field is-grouped'>
              <p class='control'>
                <%= link_to 'New Tweet', root_path, class: 'button is-info is-inverted' %>
              </p>
              <% if user_signed_in? %>
                <p class="control"> 
                  <%= link_to current_user.name, edit_user_registration_path, class: 'button is-info' %>
                </p>
                <p>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button is-info'  %>
                </p>
                <% else %>
                <p class='control'>
                <%= link_to 'Sign In', new_user_session_path, class: 'button is-info' %>
                </p><p class='control'>
                <%= link_to 'Sign Up', new_user_registration_path, class: 'button is-info' %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/my_tweets/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is-64x64">
          <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
        </p>
      </figure>
      <div class="media-content">
        <%= render 'my_tweets/form' %>
      </div>
    </article>
  <% end %>

<% @my_tweets.each do | tweet | %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
          <%= gravatar_image_tag(tweet.user.email, size: 64, alt: tweet.user.name) %>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= tweet.user.name %></strong><br/>
          <small><%= tweet.user.username %></small><br/>
          <p><%= tweet.mytweet %></p>
        </div>
        <% if user_signed_in? %>
          <nav class="level">
            <div class="level-left is-mobile">
              <%= link_to tweet, class: 'level-item' do %>
                <span class="icon"><i class='fa fa-link' aria-hidden='true'></i></span>
              <% end %>
              <%= link_to edit_my_tweet_path(tweet), class:'level-item' do %>
                <span class="icon"><i class="fa fa-pencil" aria-hidden='true'></i></span>
              <% end %>
              <%= link_to tweet, method: :delete, data: { confirm: 'Are you sure you want to delete this tweet?' } do %>
                <span class="icon"><i class="fa fa-trash-o" aria-hidden='true'></i></span>
              <% end %>
            </div>
          </nav>
        <% end  %>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/my_tweets/_form.html.erb
<%= simple_form_for(@my_tweet) do |f|  %>
<%= f.error_notification %>
<div class="field">
  <div class="control">
    <%= f.input :mytweet, label: "Tweet about it", input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label' }, autofocus: true, placeholder: 'Composing a new Tweet...' %>
  </div>
</div>
<%= f.button :submit, class: 'button is-info' %>
<% end %>

app/views/my_tweets/_profile.html.erb
<column class="is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong>
              </br>
              <small><%= current_user.username %></small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">My Tweets</p>
            <p class="title is-6"><%= current_user.my_tweet.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">123</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Tweets</p>
            <p class="title is-6">465K </p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</column>

app/views/my_tweets/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a class="panel-block">
      Trend 1 
    </a>
    <a class="panel-block">
      Trend 2 
    </a>
    <a class="panel-block">
      Trend 3 
    </a>
    <a class="panel-block">
      Trend 4 
    </a>
    <a class="panel-block">
      Trend 5
    </a>
    <a class="panel-block">
      Trend 6 
    </a>
  </nav>
</div>

app/views/my_tweets/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to Follow</p>
  </nav>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src='https://bulma.io/images/placeholders/32x32.png'>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Smith</strong>
            <small>@johnsmith</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src='https://bulma.io/images/placeholders/32x32.png'>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Smith</strong>
            <small>@johnsmith</small>
          </p>
        </div>
      </div>
    </article>
  </div>
  <div class="panel-block">
    <article class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src='https://bulma.io/images/placeholders/32x32.png'>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <p>
            <strong>John Smith</strong>
            <small>@johnsmith</small>
          </p>
        </div>
      </div>
    </article>
  </div>
</div>

app/views/my_tweets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweeet</h1>
				<%= render 'form', tweeet: @my_tweets %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', my_tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/my_tweets/index.html.erb
<section class='section'>
  <div class='container'>
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
      <% else %>
         <%= render 'trends' %>
      <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/my_tweets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Tweeet</h1>
					<%= render 'form', tweeet: @my_tweets %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', my_tweets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/my_tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mytweet:</strong>
  <%= @my_tweet.mytweet %>
</p>

<%= link_to 'Edit', edit_my_tweet_path(@my_tweet) %> |
<%= link_to 'Back', my_tweets_path %>